### ISSUE TITLE
'vpn' is hard-coded in Dockerfile CMD

### ISSUE THREAD

**Issue by shcorya** [sjinks/docker-tinc#5]
The environmental variable `NETWORK=${NETWORK_NAME:-vpn}` loads in `entrypoint.sh`; however, 'vpn' is hard-coded in the last line of `Dockerfile`.

**Comment by shcorya** [comment]
Env. `NETWORK` can be set at the beginning of `Dockerfile`, right after the `FROM` statement.
```
FROM alpine:3.12
ENV NETWORK=vpn
RUN apk add --no-cache tinc-pre
...
```
https://docs.docker.com/engine/reference/builder/#env

>This value will be in the environment for all subsequent instructions in the build stage and can be replaced inline in many as well.

I think that by setting `ENV NETWORK=vpn` in the `Dockerfile` it does not need to be set in `entrypoint.sh` but I am not certain.

**Comment by sjinks** [comment]
I have already forgotten about this repo :-) I do have an updated version of the code, will commit it tomorrow.

As far as I remember, the issue was that the shell version of `CMD` did not allow for shell expansion. It is still possible to pass `-n my-custom-network-name` in arguments to `docker run`.

**Comment by sjinks** [comment]
Done, please take a look

**Comment by shcorya** [comment]
Just from looking at it, that looks great. This seems to be a great way to run tinc in docker. Thanks for committing that latest patch.
